In [1]:
import polars as pl
import pandas as pd

In [2]:
annotaion = pd.read_csv("../tmp/processed/450k_anno.csv", low_memory=False)

In [30]:
data1 = pd.read_csv("../tmp/processed/GSE105018_chr18.csv", index_col="ID")
data2 = pd.read_csv("../tmp/processed/GSE55763_chr18.csv", index_col="ID")

In [31]:
data2

,X7471147002_R01C01,X7471147002_R01C02,X7471147002_R02C01,X7471147002_R02C02,X7471147002_R03C01,X7471147002_R03C02,X7471147002_R04C01,X7471147002_R04C02,X7471147002_R05C01,X7471147002_R05C02,...,X7786915047_R02C02,X7786915157_R03C01,X7786915157_R04C01,X7786915157_R04C02,X7786915157_R06C01,X7471147081_R06C01,X7786915035_R05C01,X7512551008_R06C01,X7786915069_R03C01,X7512551008_R05C02
ID,,,,,,,,,,,,,,,,,,,,,
cg13587056,0.676640,0.693647,0.666248,0.700082,0.678176,0.610874,0.685709,0.722715,0.755983,0.642503,...,0.728166,0.708495,0.676888,0.725762,0.760270,0.782896,0.684524,0.664040,0.702310,0.696490
cg18836174,0.732535,0.688229,0.697276,0.665160,0.735552,0.603531,0.789391,0.682745,0.649507,0.623869,...,0.724858,0.731014,0.728337,0.762800,0.607938,0.756926,0.733198,0.734800,0.634603,0.749368
cg25023094,0.778544,0.835717,0.860914,0.777796,0.821480,0.693452,0.833934,0.859021,0.750793,0.783042,...,0.821428,0.823427,0.804172,0.870684,0.869332,0.770828,0.801441,0.867154,0.824067,0.813419
cg06469293,0.732087,0.744752,0.732468,0.707702,0.722186,0.701003,0.765638,0.754980,0.754505,0.728799,...,0.763250,0.752912,0.735169,0.777863,0.748781,0.736980,0.690319,0.784550,0.755471,0.777889
cg23955402,0.765238,0.779951,0.786995,0.771751,0.768398,0.743732,0.780454,0.781401,0.788176,0.779840,...,0.788524,0.798621,0.802972,0.796840,0.786740,0.790340,0.795994,0.801191,0.819896,0.811264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cg23374700,0.087422,0.100004,0.074596,0.056191,0.088389,0.069025,0.109468,0.075793,0.078543,0.071436,...,0.109881,0.086371,0.078847,0.110032,0.103076,0.090886,0.099742,0.100529,0.090987,0.141367
cg23686403,0.060740,0.083293,0.072600,0.065581,0.079492,0.062647,0.092593,0.068292,0.081740,0.069846,...,0.100881,0.057230,0.073832,0.064586,0.067373,0.076894,0.092618,0.075520,0.087859,0.102236
cg05872073,0.027777,0.034588,0.009666,0.015405,0.013139,0.049732,0.039555,0.034697,0.027070,0.016198,...,0.025132,0.020870,0.016587,0.021354,0.020526,0.016702,0.016185,0.013898,0.022663,0.028070
cg00870662,0.073108,0.077900,0.054419,0.042247,0.034487,0.021651,0.059149,0.071989,0.060161,0.056286,...,0.060037,0.047601,0.058069,0.051892,0.054369,0.050000,0.057843,0.104520,0.057110,0.070394
cg00234655,0.752732,0.822276,0.763893,0.749941,0.767755,0.779863,0.767439,0.757207,0.807398,0.788653,...,0.776455,0.785196,0.718849,0.736517,0.739005,0.753336,0.783490,0.742422,0.756487,0.749800

In [32]:
data2.isna().sum(axis = 1)

ID
cg13587056    0
cg18836174    0
cg25023094    0
cg06469293    0
cg23955402    0
             ..
cg23374700    0
cg23686403    0
cg05872073    0
cg00870662    0
cg00234655    0
Length: 5922, dtype: int64

In [33]:
data2.fillna(data2.mean(), inplace=True)

In [34]:
data2

,X7471147002_R01C01,X7471147002_R01C02,X7471147002_R02C01,X7471147002_R02C02,X7471147002_R03C01,X7471147002_R03C02,X7471147002_R04C01,X7471147002_R04C02,X7471147002_R05C01,X7471147002_R05C02,...,X7786915047_R02C02,X7786915157_R03C01,X7786915157_R04C01,X7786915157_R04C02,X7786915157_R06C01,X7471147081_R06C01,X7786915035_R05C01,X7512551008_R06C01,X7786915069_R03C01,X7512551008_R05C02
ID,,,,,,,,,,,,,,,,,,,,,
cg13587056,0.676640,0.693647,0.666248,0.700082,0.678176,0.610874,0.685709,0.722715,0.755983,0.642503,...,0.728166,0.708495,0.676888,0.725762,0.760270,0.782896,0.684524,0.664040,0.702310,0.696490
cg18836174,0.732535,0.688229,0.697276,0.665160,0.735552,0.603531,0.789391,0.682745,0.649507,0.623869,...,0.724858,0.731014,0.728337,0.762800,0.607938,0.756926,0.733198,0.734800,0.634603,0.749368
cg25023094,0.778544,0.835717,0.860914,0.777796,0.821480,0.693452,0.833934,0.859021,0.750793,0.783042,...,0.821428,0.823427,0.804172,0.870684,0.869332,0.770828,0.801441,0.867154,0.824067,0.813419
cg06469293,0.732087,0.744752,0.732468,0.707702,0.722186,0.701003,0.765638,0.754980,0.754505,0.728799,...,0.763250,0.752912,0.735169,0.777863,0.748781,0.736980,0.690319,0.784550,0.755471,0.777889
cg23955402,0.765238,0.779951,0.786995,0.771751,0.768398,0.743732,0.780454,0.781401,0.788176,0.779840,...,0.788524,0.798621,0.802972,0.796840,0.786740,0.790340,0.795994,0.801191,0.819896,0.811264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cg23374700,0.087422,0.100004,0.074596,0.056191,0.088389,0.069025,0.109468,0.075793,0.078543,0.071436,...,0.109881,0.086371,0.078847,0.110032,0.103076,0.090886,0.099742,0.100529,0.090987,0.141367
cg23686403,0.060740,0.083293,0.072600,0.065581,0.079492,0.062647,0.092593,0.068292,0.081740,0.069846,...,0.100881,0.057230,0.073832,0.064586,0.067373,0.076894,0.092618,0.075520,0.087859,0.102236
cg05872073,0.027777,0.034588,0.009666,0.015405,0.013139,0.049732,0.039555,0.034697,0.027070,0.016198,...,0.025132,0.020870,0.016587,0.021354,0.020526,0.016702,0.016185,0.013898,0.022663,0.028070
cg00870662,0.073108,0.077900,0.054419,0.042247,0.034487,0.021651,0.059149,0.071989,0.060161,0.056286,...,0.060037,0.047601,0.058069,0.051892,0.054369,0.050000,0.057843,0.104520,0.057110,0.070394
cg00234655,0.752732,0.822276,0.763893,0.749941,0.767755,0.779863,0.767439,0.757207,0.807398,0.788653,...,0.776455,0.785196,0.718849,0.736517,0.739005,0.753336,0.783490,0.742422,0.756487,0.749800